# Generated by Django 3.1.3 on 2020-11-25 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='변호사_응답')),
            ],
            options={
                'verbose_name': '변호사_응답',
                'verbose_name_plural': '변호사_응답',
                'db_table': 'answers',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=20, verbose_name='태그')),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그',
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='제목')),
                ('description', models.TextField(verbose_name='설명')),
                ('satisfaction', models.BooleanField(blank=True, null=True, verbose_name='AI검색_만족')),
                ('tags', models.ManyToManyField(blank=True, to='core.Tag', verbose_name='태그')),
            ],
            options={
                'verbose_name': '변호사_질문',
                'verbose_name_plural': '변호사_질문',
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(blank=True, default='', max_length=11, verbose_name='연락처')),
                ('code', models.CharField(blank=True, max_length=12, null=True, verbose_name='코드')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_answer', to='core.answer', verbose_name='변호사_응답')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_question', to='core.question', verbose_name='변호사_질문')),
            ],
            options={
                'verbose_name': '이벤트',
                'verbose_name_plural': '이벤트',
                'db_table': 'events',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='law_question', to='core.question', verbose_name='변호사_질문'),
        ),
        migrations.CreateModel(
            name='AIAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='AI검색_결과')),
                ('satisfaction', models.BooleanField(blank=True, null=True, verbose_name='AI응답_만족')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_question', to='core.question', verbose_name='AI검색_질문')),
            ],
            options={
                'verbose_name': 'AI검색_응답',
                'verbose_name_plural': 'AI검색_응답',
                'db_table': 'ai_answers',
            },
        ),
    ]
