# Generated by Django 3.1.3 on 2020-11-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(null=True, verbose_name='변호사_응답'),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='제목'),
        ),
    ]
