# Generated by Django 3.1.3 on 2020-11-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201126_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='phonenumber',
            field=models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='연락처'),
        ),
    ]
