# Generated by Django 3.1.3 on 2020-11-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201126_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianswer',
            name='answer',
            field=models.JSONField(default=dict, verbose_name='AI검색_결과'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='event',
            name='answer',
            field=models.TextField(null=True, verbose_name='변호사_응답'),
        ),
    ]
