# Generated by Django 3.1.3 on 2020-11-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201127_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanryeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='판례코드')),
                ('jurisdiction', models.TextField(blank=True, null=True, verbose_name='판시사항')),
            ],
            options={
                'verbose_name': '판시사항',
                'verbose_name_plural': '판시사항',
                'db_table': 'panryes',
            },
        ),
    ]
