# Generated by Django 3.1.3 on 2020-11-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201129_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianswer',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='AI검색_설명'),
        ),
        migrations.AddField(
            model_name='aianswer',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='AI검색_제목'),
        ),
    ]
