# Generated by Django 3.1.3 on 2020-11-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201129_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcomp',
            name='manager',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='담당자'),
        ),
        migrations.AlterField(
            model_name='aianswer',
            name='inserted_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록 시간'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='inserted_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록 시간'),
        ),
        migrations.AlterField(
            model_name='event',
            name='inserted_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록 시간'),
        ),
        migrations.AlterField(
            model_name='eventcomp',
            name='email',
            field=models.CharField(max_length=100, unique=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='eventcomp',
            name='inserted_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록 시간'),
        ),
        migrations.AlterField(
            model_name='question',
            name='inserted_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록 시간'),
        ),
    ]
