# Generated by Django 3.1.3 on 2020-11-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201129_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panryedata',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='판례코드'),
        ),
    ]
